### ISSUE TITLE
Error while trying to add new model item

### ISSUE THREAD

**Issue by glebcha** [rs-pro/rails_admin_state#7]
Railsadmin latest, Rails 4.1

```
 /usr/local/rvm/gems/ruby-2.0.0-p353/bundler/gems/rails_admin_state-8bd04c93ce00/app/views/rails_admin/main/_form_state.html.haml 
```

undefined method `state_event'

 .state-widget
    = form.hidden_field field.method_name.to_s + '_event' **(here it came from and it correspond to implemented CanCan support I guess)**
    = field.form_value
    :javascript
      $(function() {

**Comment by SuperMasterBlasterLaser** [comment]
I have encountered this problem too. I just forked this gem and changed `_form_state.html.haml`'s `_event` to `_events`. It shows me my event buttons. However, IT DOES NOTHING AND DOES NOT CHANGE THE STATE OF MODEL AFTER SAVING.

I think this gem is not supported.

**Comment by glebtv** [comment]
Gem works fine, check your transitions / validations.

**Comment by SuperMasterBlasterLaser** [comment]
@glebtv Wow. After two years you have replied XD
